
services:
  file-server:
    build:
      context: .
      dockerfile: ./src/File.HttpApi.Host/Dockerfile
    container_name: file-server
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
